[package]
name = "simple_station_game"
version = "0.1.0"
authors = ["Syst3mz <ethanansburgstda@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
